name: openinsitute_core
description: Shared code for OI apps
version: 0.0.1
# homepage:

environment:
  sdk: ">=2.15.0-116.0.dev <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  xml: ^6.1.0
  http: ^1.1.0
  web_socket_channel: ^2.1.0
  shared_preferences: ^2.0.15
  json_serializable: ^6.1.4
  json_annotation: ^4.4.0
  firebase_auth: ^4.10.0
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  # isar: ^2.2.1
  # isar_flutter_libs: ^2.2.1 # contains the binaries (not required for web)
  path_provider: ^2.0.9
  connectivity_plus: ^4.0.2
  internet_connection_checker: ^1.0.0+1
  http_interceptor: ^2.0.0-beta.7
  permission_handler: ^11.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.0.0
  isar_generator: ^3.0.4
  hive_generator: ^2.0.0
  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.8
  flutter_local_notifications: ^15.1.1
  mockito: ^5.2.0
  firebase_auth_mocks: ^0.12.0

  hive_test: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - system/
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
